---
name: lab-01
break: true
indent: 4
---
 
writing:
    reflection.md:
        ConfirmFileExists
        CountFileParagraphs --count 5
        MatchFileFragment --fragment "{YOUR NAME HERE}" --count 0
 
home:
    ulysses-1.jpeg:
        ConfirmFileExists

home:
    ulysses-2.jpeg:
        ConfirmFileExists
        
home:
    ulysses-3.jpeg:
        ConfirmFileExists
        
home:
    ulysses-4.jpeg:
        ConfirmFileExists
        
home:
    ulysses-5.jpeg:
        ConfirmFileExists
        
home:
    ulysses-6.jpeg:
        ConfirmFileExists
        
CountCommits --count 2